apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: project
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: static-files-pv
          persistentVolumeClaim:
            claimName: todo-project-pvc
      containers:
        - name: todo-app
          image: PROJECT/APP_IMAGE
          env:
            - name: PORT
              value: "8080"
            - name: TODO_API_URL
              value: "http://todo-api-svc/todos"
            - name: FILES_PATH
              value: /static
          volumeMounts:
            - name: static-files-pv
              mountPath: /static
