apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: PROJECT/API_IMAGE
          env:
            - name: PORT
              value: "8083"
            - name: DB_HOST
              value: postgres-svc
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-pw
                  key: DB_PASSWORD
