apiVersion: v1
kind: Service
metadata:
  name: todo-api-svc
  namespace: project
spec:
  type: NodePort
  selector:
    app: todo-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8083
