apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: jankoskin/ping-pong@sha256:612bec15a70367224c3f728b610a9354bb10475448e037e7c21268cb65488217
          env:
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-pw
                  key: DB_PASSWORD
            - name: DB_HOST
              value: postgres-svc
