apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: jankoskin/ping-pong@sha256:58b155e9bc4f9204dee66a3758b2763d9b2251b1172b776011d7344e1f631e3e
          env:
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-pw
                  key: DB_PASSWORD
            - name: DB_HOST
              value: postgres-svc
