apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
  namespace: apps
spec:
  type: LoadBalancer
  selector:
    app: ping-pong
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3001
