apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/namespace.yaml
  - manifests/persistentvolumeclaim.yaml
  - todo-api/manifests/secret.yaml
  - todo-api/manifests/statefulset.yaml
  - todo-api/manifests/deployment.yaml
  - todo-api/manifests/service.yaml
  - todo-app/manifests/deployment.yaml
  - todo-app/manifests/service.yaml
  - todo-api/manifests/cronjob.yaml
  - manifests/ingress.yaml
images:
  - name: PROJECT/API_IMAGE
    # This will be set by CI
    newName: jankoskin/todo-api
  - name: PROJECT/APP_IMAGE
    # This will be set by CI
    newName: jankoskin/todo-app
