apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-project-pvc # name of the volume claim, this will be used in the deployment
spec:
  storageClassName: todo-project-pv # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
