apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: apps
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: log-output-vol
          persistentVolumeClaim:
            claimName: apps-pv-claim
        - name: config-vol
          configMap:
            name: config
            items:
              - key: "information.txt"
                path: "information.txt"
      containers:
        - name: log-output-ticker
          image: jankoskin/log-output-ticker@sha256:f2d7e4875a516551f59ee4e5ada7c496e3b809c7d3e5c8e756a69871e86f476e
          env:
            - name: LOGS_PATH
              value: /logs
          volumeMounts:
            - name: log-output-vol
              mountPath: /logs
        - name: log-output-handler
          image: jankoskin/log-output-handler@sha256:61360ff08d46eb3155ba4cd448d7f1fb8949b7fd921f63812766aa1cb6ab54eb
          env:
            - name: LOGS_PATH
              value: /logs
            - name: CONFIG_PATH
              value: /config
            - name: PING_PONG_URL
              value: "http://ping-pong-svc/ping-pong"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: message
          volumeMounts:
            - name: log-output-vol
              mountPath: /logs
            - name: config-vol
              mountPath: /config
              readOnly: true
