apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: log-output-vol
          persistentVolumeClaim:
            claimName: apps-pv-claim
      containers:
        - name: log-output-ticker
          image: jankoskin/log-output-ticker@sha256:37e37f5589b1f128dc581cacf961d9e2baec2c94dffedff25cf1a19a12580c33
          env:
            - name: LOGS_PATH
              value: /logs
          volumeMounts:
            - name: log-output-vol
              mountPath: /logs
        - name: log-output-handler
          image: jankoskin/log-output-handler@sha256:3bc13a6c9df63f0f2eb659625d986bcc84eba99f431656ca714325f6d77d196a
          env:
            - name: LOGS_PATH
              value: /logs
            - name: PING_PONG_URL
              value: "http://ping-pong-svc:3001/ping-pong"
          volumeMounts:
            - name: log-output-vol
              mountPath: /logs
