name: Delete Application

on:
  delete:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  APP_IMAGE: todo-app
  API_IMAGE: todo-api
  BRANCH: ${{ github.ref_name }}
  NAMESPACE: project
  SOPS_AGE_KEY: ${{ secrets.AGE_KEY }}

jobs:
  delete-environment:
    name: Delete Environment
    runs-on: ubuntu-latest
    environment: dwk
    if: github.event.ref_type == 'branch'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2

      - name: "Use gcloud CLI"
        run: gcloud info

      - run: gcloud --quiet auth configure-docker

      - name: "Get GKE credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "${{ env.GKE_CLUSTER }}"
          project_id: "${{ env.PROJECT_ID }}"
          location: "${{ env.GKE_ZONE }}"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Set up sops
        run: |-
          curl -L -o sops.deb https://github.com/getsops/sops/releases/download/v3.9.2/sops_3.9.2_amd64.deb
          sudo apt install -y ./sops.deb

      - name: Prepare secrets
        run: |-
          sops --decrypt ./project/todo-api/manifests/secret.enc.yaml > ./project/todo-api/manifests/secret.yaml

      - name: Set namespace
        if: ${{ env.BRANCH != 'main' }}
        run: echo "NAMESPACE=project-$BRANCH" >> $GITHUB_ENV

      - name: Delete
        run: |-
          pushd ./project
          kubectl config set-context --current --namespace=$NAMESPACE
          kustomize edit set namespace $NAMESPACE
          kustomize build . | kubectl delete -f -
          popd
